CREATE TABLE `inbound_leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadName` varchar(255) NOT NULL,
	`dateReceived` timestamp,
	`referringFacility` varchar(255),
	`facilityContact` varchar(255),
	`assignedAgent` varchar(100),
	`caseType` varchar(100),
	`signed` boolean DEFAULT false,
	`signedDate` timestamp,
	`notSignedReason` text,
	`countsTowardPartnerActivity` boolean DEFAULT true,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inbound_leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `outbound_referrals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`filevineLinkOrRef` varchar(500),
	`clientAddress` text,
	`clientCity` varchar(100),
	`clientZip` varchar(20),
	`dateSigned` timestamp,
	`referralNeeded` boolean DEFAULT true,
	`referralType` varchar(100),
	`assignedAgent` varchar(100),
	`recommendedFacility` varchar(255),
	`facilityOwner` varchar(100),
	`distanceTravelTime` varchar(100),
	`reasonForSelection` text,
	`referralSentDate` timestamp,
	`status` enum('Pending Review','Assigned to Agent','Facility Selected','Referral Sent','Facility Confirmed','Client Scheduled','Client Attended','Issue / Needs Follow-Up','Completed','Not Referred') NOT NULL DEFAULT 'Pending Review',
	`followUpDate` timestamp,
	`facilityConfirmed` boolean DEFAULT false,
	`clientScheduled` boolean DEFAULT false,
	`clientAttended` boolean DEFAULT false,
	`facilityHadSentLeads` boolean DEFAULT false,
	`notes` text,
	`lastUpdatedBy` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `outbound_referrals_id` PRIMARY KEY(`id`)
);
